# Font
font_size 14.0

# Cursor
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Scrolling
scrollback_lines 6000
scrollback_pager_history_size 10

# Mouse
mouse_hide_wait 3.0

# Window
hide_window_decorations yes

# Tab Bar
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 2.0 2.0
tab_bar_style powerline
tab_bar_min_tabs 2

# Appearance
background_opacity 0.80
background_blur 2

# macOS
macos_option_as_alt both

# Neovim
map cmd+d send_text all \x04
map cmd+u send_text all \x15
map cmd+p send_text all \x10
map cmd+n send_text all \x0e
map cmd+j send_text all \x0a
map cmd+k send_text all \x0b
map cmd+b send_text all \x02
map cmd+l send_text all \x0c
map cmd+h send_text all \x08
